// Build the VS Code preview's webview bundle: the parser's pure core + this
// package's renderer + KaTeX + Mermaid, as one browser IIFE exposing
// `window.GEML`. Output lands in ../vscode/media/, alongside KaTeX's fonts.
//
// It lives here, not in the vscode package, for the same reason
// playground.build.mjs does: this package owns the renderer, the node-module
// stubs, the esbuild dependency and the KaTeX/Mermaid versions. A second
// esbuild configuration in another directory would be a second place for the
// alias list to go stale — and the alias list is exactly what makes a
// node-targeted parser survive in a browser.
import * as esbuild from "esbuild";
import { existsSync, mkdirSync, readdirSync, copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const stub = resolve(root, "src/node-stub.js");
const parserDist = resolve(root, "../../geml-parser/dist/geml.js");
const outDir = resolve(root, "../vscode/media");

if (!existsSync(parserDist)) {
  console.error("geml-parser is not built. Run: cd ../../geml-parser && npm install && npm run build");
  process.exit(1);
}

await esbuild.build({
  entryPoints: [resolve(outDir, "entry.js")],
  bundle: true,
  format: "iife",
  platform: "browser",
  // VS Code webviews run on the Electron Chromium that ships with the editor;
  // the engines floor (^1.75) is comfortably past chrome110.
  target: "chrome110",
  outfile: resolve(outDir, "geml-webview.js"),
  loader: { ".css": "text" },
  define: { "process.argv": "[]", "import.meta.url": "\"\"" },
  alias: { "node:fs": stub, "node:path": stub, "node:crypto": stub, "node:url": stub, "node:child_process": stub, "node:os": stub },
  // entry.js lives outside this package, so bare imports (katex, mermaid) have
  // to be resolved from here.
  nodePaths: [resolve(root, "node_modules")],
  logLevel: "info",
});

// The two stylesheets go in as FILES, not as strings inside the bundle, for two
// reasons the page depends on: KaTeX's `url(fonts/KaTeX_*.woff2)` resolves
// against the stylesheet's own URL (so media/fonts/ just works), and the pane's
// theme overrides in preview.css land last in the cascade because they are the
// last <link>. Injecting either from script breaks one or the other.
const banner = (from) =>
  `/* GENERATED by integrations/geml-viewer/vscode.build.mjs — copied from ${from}.\n` +
  `   Do not edit: the next build overwrites it. */\n`;

const copyCss = (src, out, from) => {
  writeFileSync(out, banner(from) + readFileSync(src, "utf8"));
};
copyCss(resolve(root, "src/geml.css"), resolve(outDir, "geml.css"), "integrations/geml-viewer/src/geml.css");
copyCss(resolve(root, "node_modules/katex/dist/katex.css"), resolve(outDir, "katex.css"), "katex/dist/katex.css");
console.log("copied geml.css + katex.css -> vscode/media");

const fontsSrc = resolve(root, "node_modules/katex/dist/fonts");
const fontsOut = resolve(outDir, "fonts");
if (existsSync(fontsSrc)) {
  mkdirSync(fontsOut, { recursive: true });
  let n = 0;
  for (const f of readdirSync(fontsSrc)) {
    // woff2 only: every browser the webview can be is fine with it, and the
    // ttf/woff fallbacks triple the size of the vsix for nobody.
    if (!f.endsWith(".woff2")) continue;
    copyFileSync(resolve(fontsSrc, f), resolve(fontsOut, f));
    n++;
  }
  console.log(`copied ${n} KaTeX woff2 font(s) -> vscode/media/fonts`);
}
console.log("built vscode/media/geml-webview.js");
